# -*- coding: utf-8 -*-
"""spell_checker_app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13rr8OfbkabegfJbwgPEUtT3AoDipY1Xe
"""

# Save this code to a file, e.g., spell_checker_app.py

import streamlit as st
from spellchecker import SpellChecker

# Initialize the spell checker
spell = SpellChecker()

st.title("Interactive Spell Checker")

# Create a text input field
text = st.text_input("Enter a word to check for spelling errors:")

if text:
    if text.lower() == "exit":
        st.write("You've chosen to exit.")
    else:
        if spell.correction(text) == text:
            st.write(f"'{text}' is spelled correctly.")
        else:
            suggestions = ", ".join(spell.candidates(text))
            st.write(f"'{text}' is misspelled. Suggestions: {suggestions}")
else:
    st.write("Enter a word to check for spelling errors.")